---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Collect all BIG-IP facts
      server: "{{ inventory_hostname }}"
      bigip_device_facts:
        gather_subset:
          - all