---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Collect all BIG-IP facts
      bigip_device_facts:
        gather_subset:
          - all
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
      register: facts
