---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
#    - name: create direcotry
#      file:
#        path: "{{ playbook_dir }}/.ssh"
#        state: directory

#    - name: create temp file
#      tempfile:
#        path: "{{ playbook_dir }}/.ssh"
#      register: git_temp_file
#
#    - name: copy key to temp file
#      copy:
#        content: "{{ git_key }}"
#        dest: "{{ git_temp_file.path }}"
#
    - name: Change file ownership, group and permissions
      file:
        path: "{{ playbook_dir}}/.ssh/ansible.pem"
        mode: '0600'
      delegate_to: localhost


    - name: set repo path
      set_fact:
        git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"

    - name: git clone
      git:
        repo: "{{ git_url }}"
        dest: "{{ playbook_dir }}/{{ git_repo_path }}"
        accept_hostkey: yes
        key_file: "{{ playbook_dir }}/.ssh/ansible.pem"

    - name: create backup
      bigip_command:
        server: "{{ inventory_hostname }}"
        commands: "save sys ucs cs_backup.ucs"
        validate_certs: no

    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "cs_backup.ucs"
        dest: "{{ playbook_dir }}/cs_{{ inventory_hostname }}.ucs"
        create_on_missing: yes
        force: yes
        server: "{{ inventory_hostname }}"
        fail_on_missing: yes
        validate_certs: no
      delegate_to: localhost

    - name: Remove uploaded UCS file
      bigip_ucs:
        ucs: cs_backup.ucs
        state: absent
        validate_certs: no
        server: "{{ inventory_hostname }}"
      delegate_to: localhost
