---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: create or check that git repo exists
      git:
        repo: 'https://github.com/jmcleroy/f5backups.git'
        dest: /tmp/checkout
        update: yes

    - name: create backup
      bigip_command:
        server: "{{ inventory_hostname }}"
        commands: "save sys ucs cs_backup.ucs"
        validate_certs: no

    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "cs_backup.ucs"
        dest: "{{ playbook_dir }}/cs_{{ inventory_hostname }}.ucs"
        create_on_missing: yes
        force: yes
        server: "{{ inventory_hostname }}"
        fail_on_missing: yes
        validate_certs: no
      delegate_to: localhost

    - name: Remove uploaded UCS file
      bigip_ucs:
        ucs: cs_backup.ucs
        state: absent
        validate_certs: no
        server: "{{ inventory_hostname }}"
      delegate_to: localhost