---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: create backup
      bigip_command:
        commands:
          - command: save sys ucs cs_backup.ucs
            prompt: "/var/local/ucs/cs_backup.ucs: file exists, overwrite it? (y/n)"
            answer: 'y'

    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "cs_backup.ucs"
        dest: "/tmp/cs_{{ inventory_hostname }}.ucs"
        create_on_missing: yes
        server: "{{ inventory_hostname }}"
        fail_on_missing: yes
        validate_certs: no
      delegate_to: localhost