---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
  #  - name: create backup
  #    bigip_command:
  #      commands: tmsh save sys ucs $(echo $HOSTNAME | cut -d'.' -f1)

    - name: Download a new UCS
      bigip_ucs_fetch:
        src: "cs_{{ inventory_hostname }}.ucs"
        dest: "/tmp/cs_{{ inventory_hostname }}.ucs"
        server: "{{ inventory_hostname }}"
      delegate_to: localhost