---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
    - name: Collect BIG-IP facts
      bigip_device_facts:
        gather_subset: all
      server: "{{ inventory_hostname }}""
      delegate_to: localhost