- name: F5 scf backup testing
  hosts: all
  connection: local
  gather_facts: no
  environment:
    F5_VALIDATE_CERTS: "no"

  tasks:
    - name: run show version and check to see if output contains BIG-IP
      bigip_command:
        commands: save /sys config file /tmp/{{ inventory_hostname }}.scf no-passphrase
          server: "{{ inventory_hostname}}"
      delegate_to: localhost
